feat: add colors for different states #10
Balastrong/github-stats pull request #13
Opened 2023-08-15 10:12 UTC by priyankarpal

feat: add colors for different states #10

2023-08-15 16:06 UTC, Balastrong requested changes

2023-08-15 17:51 UTC, priyankarpal commented on src/components/RepositoryContributionsCard.tsx
> +                  : 'bg-green-500'
Yeah we can do this too. But I think it's simple now, in future if we need to add more things then we should do

2023-08-16 07:04 UTC, Balastrong commented on src/components/RepositoryContributionsCard.tsx
> +                  : 'bg-green-500'
Ok you're right, it's probably too early. Thanks :)

2023-08-16 07:04 UTC, Balastrong approved these changes

2023-08-16 07:05 UTC, Balastrong commented
LGTM!

2023-08-16 07:05 UTC, merged